name: "Publish Manual Release"
on:
  workflow_dispatch:
  push: 
    branches:
      - cheetah-main
      
env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release release-candiate
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.vendor=Trifork
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch,suffix=-${{ github.run_id }}
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: build
        working-directory: opensearch-operator/
        run: make build

      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          file: opensearch-operator/Dockerfile
          context: opensearch-operator/
          push: true
          outputs: type=registry
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
